---
title: "`r titre`"
#author: "Fanny Kevin Billy"
#date: "11/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H', echo = TRUE)
```


```{r library, include=FALSE, message=FALSE, warning=FALSE}
library(RColorBrewer)
library(wordcloud)
library(dplyr)
library(ggplot2)
library(tidyverse) # transformation des dataframe
library(knitr) # kable
library(kableExtra) # kable styling
```
## `r attributes(skillsTxt())$names[1]`


```{r dataframe pour test prog, include=FALSE}
# skillsTxt<-function() {
#     skillsPrintLength<-4
#     # data frame compétence : 1ligne=1competence
#     if (skillsPrintLength>0) {
#         skillsTxt<-data.frame()
#         skillsTxt[1,1]<-"Langues : Français , A1"
#         skillsTxt[2,1]<-"Langues : Anglais , A2"
#         skillsTxt[3,1]<-"Programmation : C , 3"
#         skillsTxt[4,1]<-"Permis : B"
#         for (i in 1:skillsPrintLength) {skillsTxt[i,2]<-"Compétence"}
#     }
#     names(skillsTxt)<-c("competence","type")
#     skillsTxt
# }
# 
# actTxt<-function() {
#     actPrintLength<-12
#     # data frame compétence : 1ligne=1competence
#     if (actPrintLength>0) {
#         actTxt<-data.frame()
#         actTxt[1,1]<-"Qualité : Dynamique , 8"
#         actTxt[2,1]<-"Qualité : Autonomie , 6"
#         actTxt[3,1]<-"Qualité : Rigueur , 4"
#         actTxt[4,1]<-"Qualité : extravertie, 4"
#         actTxt[5,1]<-"Sport : velo, 1"
#         actTxt[6,1]<-"Sport : natation, 2"
#         actTxt[7,1]<-"Sport : triathlon, 4"
#         actTxt[8,1]<-"Sport : randonnée, 6"
#         actTxt[9,1]<-"Sport : nature, 9"
#         actTxt[10,1]<-"Culture : cinema, 3"
#         actTxt[11,1]<-"Culture : musique, 5"
#         actTxt[12,1]<-"Culture : voyage, 10"
#         for (i in 1:actPrintLength) {actTxt[i,2]<-"Compétence"}
#     }
#     names(actTxt)<-c("competence","type")
#     actTxt
# }
```

```{r skills, echo=FALSE, warning=FALSE}


skills<-skillsTxt() %>% 
      separate(1, c("type", "competence"), sep = ":") %>% 
      separate(competence, c("competence", "niveau"), sep = ",")


if (dim(skills)[1]>0) {
  knitr::kable(head(skills), caption = "",format="html",label="skills",booktabs = T,linesep =" ")%>%
  kable_styling(latex_options =c("striped", "HOLD_position"))  
  }

```

## `r attributes(actTxt())$names[1]`


```{r act, echo=FALSE}

if (names(actTxt())[1]==cat["act",1]) {
  act<-actTxt() %>% 
        separate(1, c("type", "act"), sep = ":") %>% 
        separate(act, c("act", "niveau"), sep = ",")
  act$niveau<-as.numeric(act$niveau)
  
  if (dim(act)[1]>11) {
  
    set.seed(1234)
    wordcloud(words = act$act, freq = act$niveau, 
            scale=c(1,.25), min.freq = 1,
             max.words=200, random.order=FALSE, rot.per=0.35, 
             colors=brewer.pal(8, "Set2"))
  } else {
  
    # Compute the position of labels
    act <- act %>% 
       arrange(desc(act)) %>%
       mutate(prop = niveau/sum(niveau)*100) %>%
       mutate(ypos = cumsum(prop)- 0.5*prop )
  
    ggplot(data=act, aes(x="",y=prop, fill=act))+
       geom_bar(width = 1, stat = "identity")+
       coord_polar("y", start=0)+
       theme_void()+ 
       theme(legend.position="none")+
       geom_text(aes(y = ypos, label = act), color = "black", size=4, nudge_x = 0.2)+ 
       scale_fill_brewer(palette="Set3")
  }
} else {
  act<-actTxt() %>% 
      separate(1, c("type", "act"), sep = ":")
  knitr::kable(head(act), caption = "",format="html",label="act",booktabs = T,linesep =" ")%>%
  kable_styling(latex_options =c("striped", "HOLD_position"))  
}
```

